// Code generated by tygo. DO NOT EDIT.

//////////
// source: client.go

export interface Client {
}

//////////
// source: events.go

export interface Workspace {
  id: number /* int */;
  name: string;
  monitor: string;
  monitorId: number /* int */;
  windows: number /* int */;
  hasfullscreen: boolean;
  lastwindow: string;
  lastwindowtitle: string;
  ispersistent: boolean;
  tiledlayout: string;
}
export interface WorkspaceRef {
  id: number /* int */;
  name: string;
}
export interface Window {
  address: string;
  mapped: boolean;
  hidden: boolean;
  at: number /* int */[];
  size: number /* int */[];
  workspace: WorkspaceRef;
  floating: boolean;
  monitor: number /* int */;
  class: string;
  title: string;
  initialClass: string;
  initialTitle: string;
  pid: number /* int */;
  xwayland: boolean;
  pinned: boolean;
  fullscreen: number /* int */;
  fullscreenClient: number /* int */;
  overFullscreen: boolean;
  grouped: string[];
  tags: string[];
  swallowing: string;
  focusHistoryID: number /* int */;
  inhibitingIdle: boolean;
  xdgTag: string;
  xdgDescription: string;
  contentType: string;
  stableId: string;
}
export interface Monitor {
  id: number /* int */;
  name: string;
  description: string;
  make: string;
  model: string;
  serial: string;
  width: number /* int */;
  height: number /* int */;
  physicalWidth: number /* int */;
  physicalHeight: number /* int */;
  refreshRate: number /* float64 */;
  x: number /* int */;
  y: number /* int */;
  activeWorkspace: WorkspaceRef;
  specialWorkspace: WorkspaceRef;
  reserved: number /* int */[];
  scale: number /* float64 */;
  transform: number /* int */;
  focused: boolean;
  dpmsStatus: boolean;
  vrr: boolean;
  solitary: string;
  solitaryBlockedBy: string[];
  activelyTearing: boolean;
  tearingBlockedBy: string[];
  directScanoutTo: string;
  directScanoutBlockedBy: string[];
  disabled: boolean;
  currentFormat: string;
  mirrorOf: string;
  availableModes: string[];
  colorManagementPreset: string;
  sdrBrightness: number /* float64 */;
  sdrSaturation: number /* float64 */;
  sdrMinLuminance: number /* float64 */;
  sdrMaxLuminance: number /* float64 */;
}
export type Broadcaster = any;
